name: CI

on:
  pull_request:
    branches:
      - main
  workflow_call:
    outputs:
      artifact-name:
        description: The name of the uploaded artifacts
        value: ${{ jobs.build.outputs.artifact-name }}
      artifact-path:
        description: The path of the uploaded artifacts
        value: ${{ jobs.build.outputs.artifact-path }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Checkout and build
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.define-vars.outputs.artifact-name }}
      artifact-path: ${{ steps.define-vars.outputs.artifact-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Define output vars
        id: define-vars
        run: |
          echo "artifact-name=myfile" >> "$GITHUB_OUTPUT"
          echo "artifact-path=myfile-*" >> "$GITHUB_OUTPUT"

      - name: Do something contrived - could also define the artifact names inline here
        run: |
          echo "1" > "myfile-$RANDOM.txt"
          echo "2" > "myfile-$RANDOM-1.txt"
          echo "3" > "myfile-$RANDOM-2.txt"

      - name: Upload artifacts
        id: upload-artifact
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v5
        with:
          name: ${{ steps.define-vars.outputs.artifact-name }}
          path: ${{ steps.define-vars.outputs.artifact-path }}
          retention-days: 7
